# -*- coding: utf-8 -*-
"""Prak Algo 8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NwMCGQ3t-_ClsirC4b-J8HmYgKgNY2X_
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def karakter_ganjil(input_string):
    karakter = ''
    for i in range(len(input_string)):
        if i % 2 == 1:
            karakter += input_string[i]
    return karakter

input_user = input("Masukkan sebuah kata: ")
hasil = karakter_ganjil(input_user)
print("Karakter indeks ganjil:", hasil)

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def hitung_jumlah_range(start, end):
    total = (end - start + 1) * (start + end) / 2
    return total

start_range = float(input("Masukkan Angka Pertama: "))
end_range = float(input("Masukkan Angka Kedua: "))

hasil = hitung_jumlah_range(start_range, end_range)
print(f"Jumlah Range adalah: ",hasil)